version: "3"
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    links:
      - mariadb:mariadb
  mariadb:
    image: "mariadb:latest"
    restart: 'always'
    volumes:
      - /var/lib/mysql/data:/db/data
      - /var/lib/mysql/logs:/db/logs
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root